### ISSUE TITLE
Deploy project on pythonanywhere

### ISSUE THREAD

**Issue by johnkeil** [johnkeil/django_rent#1]
i want to deploy my project on pythonanywhrer. so i need create custom settings file that i can run project on my local system too.

**Comment by danialrajabi** [comment]
Hi @johnkeil  , May I work on this?

**Comment by danialrajabi** [comment]
I think you want to add multiple setting file for your project like development and production setting

**Comment by johnkeil** [comment]
Hi @danialrajabi  ! Would be great,
yes i want add custom setting file
feel free to ask any question needed
