### ISSUE TITLE
adding react frontend to projects

### ISSUE THREAD

**Issue by johnkeil** [johnkeil/django_rent#2]
i dont know how can i add react frontend to my project. so if you can change my project that i can run django and react togather in one server

**Comment by danialrajabi** [comment]
if you want to use react for front end of your project, you have two options: first. run can react and django on different ports (or different servers)  and send request from react to django. second you can run them togather in one port (one server). for second option you must build static file from react project and then collect static files in django project.
i will be work at this.

**Comment by johnkeil** [comment]
hi @danialrajabi . it's look work great in my local system but when i transfer project to my pythonanywhere account it does not work. i give an error: `TemplateDoesNotExist at /`

**Comment by danialrajabi** [comment]
did you get build from react project? How did you transfer the project to the pythonanywhere account?

**Comment by johnkeil** [comment]
yes i build project in my local system and push it to github. then in the server pull it from github but i got an error!!!!!

**Comment by danialrajabi** [comment]
ok i will be check it and if find the problem i will send pull request for it
